### ISSUE TITLE
Have you seen bind-keys.el?

### ISSUE THREAD

**Issue by jwiegley** [noctuid/general.el#10]
`bind-keys`, used by `use-package`, has a great deal of overlap with this package.  Have you seen it?

**Comment by noctuid** [comment]
Yes I have (I use and love use-package). The main difference between the two is that general has good support for evil (wrapping `evil-define-key` and `evil-local-set-key`). I created this package primarily due to frustration with the limited feature set of `evil-leader` and its strange implementation. If you are wondering why I didn't instead try to contribute to `bind-key`, one reason is that despite the overlap, there are still quite a few differences in the implementation and functionality. Again the main difference is the evil support, and I don't know if you would be open to adding that to `bind-key`. My guess is that at least some of the other differences would be irreconcilable (feel free to correct me).

Right now I think the only feature that `bind-key` has that general doesn't yet have is the `describe-personal-keybindings` feature (feel free to correct me). General also has some additional functionality and differences:

General uses the same syntax as `evil-define-key` (and setq I guess) for key definitions (`key command key command...` instead of `(key . command) (key . command)`). I personally much prefer this syntax.

General uses `evil-delay` (renamed `general--delay`; I hope to clean it up a bit) in the same way `evil-define-key` does to defer keybindings until the specified keymap exists. The user could instead put their keybindings in a `use-package` statement or `eval-after-load` for the same effect, but I personally prefer less nesting.

General allows defining keys in multiple keymaps at once (this is mainly useful for evil users).

General allows buffer-local keybindings for non-evil users (`evil-local-set-key` works for this purpose with evil unlike `local-set-key`). This also has a limited use case (but is nice I think).

General has only one primary function for binding keys. All other provided commands (e.g. the vim `nmap`, `vmap`, etc. equivalents) are just wrappers for it that set different defaults or add positional arguments to emulate another key definition function. This isn't a huge deal, but I think that the provided `general-nmap`, `general-evil-define-key`, and `general-emacs-define-key` are nice.

General doesn't create new keymaps for prefix keys (this is just a difference).

**Comment by jwiegley** [comment]
You're right, that is a fair degree of difference.  Keep up the good work.

I'd be open to adding new keywords to `bind-keys`; it would be rather nice to better support evil, in fact.  But I don't want to slow you down.
