### ISSUE TITLE
Problem with global keymap

### ISSUE THREAD

**Issue by tim-millar** [noctuid/general.el#106]
```
(general-define-key
  :global-prefix "C-,"
  :states 'emacs
  "f" 'find-file)
```

The code snippet included in issue #100 is still failing for me (I'm on the latest version of general - 20180215.1455), with the following error:

```
Debugger entered--Lisp error: (wrong-type-argument keymapp global)
  lookup-key(global [emacs-state])
```

The problem seems to be with the default global keymap. The following works, OTOH:

```
(general-define-key
  :global-prefix "C-,"
  :keymap 'emacs
   "f" 'find-file)
```

**Comment by noctuid** [comment]
Are you using the latest version of evil?

**Comment by tim-millar** [comment]
Latest tagged version (i.e. on melpa-stable - 1.2.13). I'll try the latest version on melpa.

**Comment by tim-millar** [comment]
I no longer observe the same error, but it seems as though the behaviour is slightly different? The global prefix key is now shadowed in some modes - e.g., dired - where it no longer works as a leader.

**Comment by noctuid** [comment]
This is the expected behavior. See [here](https://github.com/noctuid/general.el#2018-01-20-states-normal-is-now-the-same-as-keymaps-normal). You could use `:keymaps 'global-map`. for example, instead of `:keymaps 'global` to have the old behavior. In the future, using intercept maps will be recommended instead (after a pull request I've made to evil is merged); then you would specify `:keymaps 'override`.
