### ISSUE TITLE
make general-create-definer use general-define-key

### ISSUE THREAD

**Issue by guraltsev** [noctuid/general.el#118]
You mention in the description that

`
Furthermore, general-def can only correctly replace definer statements where the first specified key is a string or vector. It will not work correctly to replace a definer that uses a variable for the first key (e.g. (global-set-key my-key 'command) cannot be replaced with general-def).
`
That is a very strange behavior and as is not documented in the actual doc string of this function. This just caused me an hour of misunderstanding. Your package is great but this behavior kind of breaks it for me. To work around this I use `general-define-key` but `general-create-definer` also uses `general-def` so it suffers from the same limitation. Could you make `general-create-definer` use the more predictable version? Thanks!

**Comment by noctuid** [comment]
I't not a strange behavior given how `general-def` works. Allowing a variable number of positional keymap/state arguments means that there is no way to automatically distinguish between `keymap-symbol` and `key-symbol`. You can still use a variable for the first key with `general-def`, but it must be separated from the positional arguments (e.g. either with a real or bogus keyword argument):

```elisp
(general-def some-map
  :start-maps t
  some-key some-command)
```

This could potentially be avoided if you consistently suffixed your keys with something that no state or keymap is suffixed with (e.g. `-key`). I could add an option to detect a symbol as a key and you could write `(general-def some-map some-key some-command)` as you'd expect. I don't really like this as a solution since it's not 100% foolproof (e.g. if I created a `which-key` evil state, it would think that state is a key).e

You can always just use the macro `general-def` would end up calling instead. All of these macros should always work as drop-in replacements (depending on the value of `general-implicit-kbd`):
```elisp
(general-emacs-define-key some-map some-key some-command)
```

> Could you make general-create-definer use the more predictable version?

I could add an option to wrap a definer other than `general-def` and update `general-def`'s docstring if that would be sufficient.

As for the example you give in #117, you can have the same result without ever needing to use a variable as the first key. General can automatically create prefix maps/commands (though this is usually unnecessary unless you plan on binding different keys to the prefix map in different keymaps).
```elisp
(general-create-definer gumacs/km/leader/def
  :prefix "M-,"
  :prefix-map 'gumacs/km/leader/map
  :prefix-name "gumacs leader keymap for gumacs/km/leader/key")

(gumacs/km/leader/def "d" 'dired)

;; I'd then just do
(general/km/leader/def
 :infix "b"
 "B" 'ibuffer)
;; or
(setq gumacs/km/buffer/key "b")
(general/km/leader/def
 :infix gumacs/km/buffer/key
 "B" 'ibuffer)

;; but you could also create a new definer
(general-create-definer gumacs/km/buffer/def
  :keymaps 'gumacs/km/leader/map
  :prefix "b"
  :prefix-map 'gumaks/km/buffer/map)
(gumacs/km/buffer/def "B" 'ibuffer)
```

If you think there is a good use case for having a variable as the first key often enough that the `:start-maps t` workaround would become annoying, I could allow for something like this:

```elisp
(general-create-definer name
  :wrapping 'general-emacs-define-key
  ...)
```

The downside of this is of course that the new definer would always require exactly one positional argument. That, or I would have to create a version of `general-def` that required quoting keymaps (no longer a drop-in replacement for any default definers).

Sorry for the inconvenience, and let me know what you think.

**Comment by guraltsev** [comment]
Thank you for the clarification. I am an emacs beginner and I have recently declared `.emacs.d` bankruptcy and I was starting to define organize everything cleanly anew. 

I believe that defining the keymap first and then assigning it later to the prefix key actually helps organization in certain circumstances but this is just how I tried going about it. 

For now I will use the `:start-maps t` method but I believe 
```
(general-create-definer name
  :wrapping 'general-emacs-define-key
  ...)
``` 
is a great and very clean idea. 

Also, to elaborate on defining a keymap without binding it first: It would be great to be able to have the possibility of writing something like this
```(general-create-definer gumacs/km/buffer/def
  :keymaps 'gumacs/km/leader/map
  :prefix "b"
  :prefix-map 'gumacs/km/buffer/map)
```
but without an explicit prefix and assigning it later like
```
(general-create-definer gumacs/km/buffer/def
  :keymaps nil
  :prefix ""
  :ignore t
  :prefix-map 'gumacs/km/buffer/map)
```
that would create the keymap without having to resort to more low-level `(make-sparse-keymap)`! Everything would be done using `leader` commands. 

Finally I have to understand how to assign a which-key description to the keymap in this case. I mean, once I define `gumacs/km/buffer/map` and I assign it under `gumacs/km/buffer/map` I would want which-key to call it something like "b  buffer..." but I will try to figure that out and if I fail I will post another issue. 

Thank you very much for the package and your help!

**Comment by noctuid** [comment]
I'll add the `:wrapping` keyword when I get the chance. I may also add something like `general-defq` (probably with a better name) that would still have the flexibility of `general-def` but require quoting keymaps like `general-define-key`:
```elisp
;; act like `global-set-key'
(general-defq "key" #'def)
;; lists and quoted arguments are positional arguments
(general-defq 'dired-mode-map ...)
(general-defq 'normal '(org-mode-map markdown-mode-map) ...)
;; variables now always work
(general-defq my-quit-key #'quit-window)
```

I'll update the documentation to make this limitation more clear, but I don't think it's a use case a lot of people need, so I'm keeping `general-def` as the default.

> I believe that defining the keymap first and then assigning it later to the prefix key actually helps organization 

Well you actually can create a prefix keymap using `general-define-key` without binding any keys. I don't understand exactly what you want from your example, but maybe this is closer to what you want than the last example that I gave:

```elisp
;; only create keymap
(general-define-key :prefix-map 'gumacs/km/leader/map)
;; or create and bind "M-," to keymap
(general-define-key
 :prefix "M-,"
 :prefix-map 'gumacs/km/leader/map)

;; create buffer prefix map
(general-define-key :prefix-map 'gumacs/km/buffer/map)
;; or create the map, bind it in `gumacs/km/leader/map', and give it a which key
;; description
(general-define-key
 :keymaps 'gumacs/km/leader/map
 :prefix "b"
 ;; using :prefix-command so that which-key can match against the command name
 :prefix-command 'gumacs/km/buffer/command
 :prefix-map 'gumacs/km/buffer/map
 :wk-full-keys nil
 "" '(:ignore t :which-key "some description"))

;; the custom definers could them be written like this
(general-create-definer gumacs/km/leader/def
  :keymaps 'gumacs/km/leader/map)

(general-create-definer gumacs/km/buffer/def
  :keymaps 'gumacs/km/buffer/map)
```

If you define both prefixes at the same time, adding a which key description with general keywords is less convoluted:
```elisp
(general-define-key
 :prefix "M-,"
 :prefix-map 'gumacs/km/leader/map
 "b" '(:prefix-command gumacs/km/buffer/map :wk "description"))

(general-create-definer gumacs/km/leader/def
  :keymaps 'gumacs/km/leader/map)

(general-create-definer gumacs/km/buffer/def
  :keymaps 'gumacs/km/buffer/map)
```

Of course, if you don't need named keymaps, you could just do:
```elisp
;; variables could be used instead of keys
(general-create-definer gumacs/km/leader/def
  :prefix "M-,")

(general-create-definer gumacs/km/buffer/def
  :prefix "M-, b")

;; or with the new :wrapping
(general-create-definer gumacs/km/buffer/def
  :wrapping 'gumacs/km/leader/map
  :infix "b")
```

I assume that you want or need the named keymaps though.

**Comment by noctuid** [comment]
@justbur I think I've asked this before, but is there an option (or could there be one) to use the keymap prompt as the which-key display string?

**Comment by justbur** [comment]
@noctuid It depends on the context. If you're using one of the functions to display a keymap directly, like `which-key-show-keymap` then it shouldn't be that hard to add. If it's during an arbitrary key sequence, then it's both harder and possibly ambiguous. which-key uses the output from `describe-buffer-bindings` to determine what keybindings are currently active. This output doesn't have the keymap prompts, so I'd need to come up with a reliable way to get it. There's also the problem that it isn't true that a prefix key always leads to bindings within the same keymap, so you'd have to decide what to show there.

**Comment by noctuid** [comment]
@guraltsev Alright, `:wrapping` now exists, and I've improved the documentation. The argument should not be quoted (e.g. `:wrapping general-emacs-define-key`).

@justbur
Thanks for the explanation. I'm not at all familiar with how which-key works internally, but would it be possible to use `key-binding` or `lookup-key` to get the actual keymap for keys identified by `describe-buffer-bindings` as keymaps? I'm guessing this isn't possible or can't be used consistently; I haven't checked if it's possible to query the current incomplete key sequence, and there are probably other complicating issues.
