### ISSUE TITLE
Current version of general still requires emacs 24.4?

### ISSUE THREAD

**Issue by ipstone** [noctuid/general.el#138]
Hello,

Similarly to issue 3 (closed, https://github.com/noctuid/general.el/issues/3), when I am using general on a emacs 24.3 machine, I got the emacs 24.4 dependency error. This requirement seems to be removed, somehow it still shows up.

Is the requirement added back, or added back inadvertently?

Thanks

**Comment by noctuid** [comment]
Yes, it's intentional (see 57165b92720515fb77177acec77667fe90aedb5c). 24.4 has been out for over four years, and I'd rather not try to maintain compatibility with older versions. If you can't update, you could try manually removing the 24.4 dependency. Most of the functionality may work, but you may also have to manually add definitions for `macrop` and `with-eval-after-load` (only used once now), for example.
