### ISSUE TITLE
More than one prefix

### ISSUE THREAD

**Issue by AssailantLF** [noctuid/general.el#15]
This might fall under the category of feature request more than a bug. Perhaps I'm unaware of how to properly do this.

To elaborate: I'm using general.el with Evil and have `SPC` as a prefix, and `C-SPC` as a non-normal-prefix. I would like to be able to have `:prefix` set to both `SPC` and `C-SPC` just to slightly simplify things.

I tried this (I left out the rest of my bindings besides the first):

    (general-define-key
     :states '(normal motion insert emacs)
     :prefix "SPC" "C-SPC"
     :non-normal-prefix "C-SPC"
     "TAB" 'other-window)

and got this error: `Wrong type argument: arrayp, other-window`

I figure that this is either **A:** not supported yet, **B:** too difficult to implement, or **C:** can be done with different syntax. If it can be done, I think it'd be pretty convenient.

Thanks for the awesome package!

**Comment by noctuid** [comment]
I didn't initially add support for binding multiple prefixes because I thought it would be redudant and not very useful. There is a `:global-prefix` keyword (currently not documented in the readme; see #12) that you can use though (in this case instead of `:non-normal-prefix`). Does that work for your use case?

**Comment by AssailantLF** [comment]
Yeah, `:global-prefix` works perfectly for what I wanted, and makes more sense syntactically. Thanks!

**Comment by noctuid** [comment]
Great. Let me know if you have any other suggestions.
