### ISSUE TITLE
Release on melpa-stable

### ISSUE THREAD

**Issue by 4lex1v** [noctuid/general.el#188]
Hi!
Thank you for your great work on the package! I was wondering if you would consider cutting a release for melpa-stable repository?

**Comment by husainaloos** [comment]
I ran into the fact that this is not available in melpa stable. Is there interest in bringing this to melpa stable?

**Comment by alphapapa** [comment]
FYI: https://github.com/melpa/melpa/issues/6656

**Comment by noctuid** [comment]
Use MELPA. The tests cover almost all functionality, and master has been stable for years. I agree with @alphapapa about MELPA stable. Almost all new commits from me will be bugfixes. I would basically be tagging a release every new commit, and MELPA and MELPA stable would be no different. At some point I will finish a minimum rewrite of general (probably under a new package name), and I will tag frequent releases for new functionality/bugfixes, but even then I won't recommend MELPA stable because I don't see how it is useful.

At best, MELPA stable protects you from intermediate, newly introduced bugs (less of a problem with tests and good development practices). This only works well with packages developed with stable releases in mind (e.g. some period of testing/bugfixes only before a release or releases can also have newly introduced bugs). My experiences has been that breaking changes are more of an issue than newly introduced bugs, and MELPA stable does nothing to help with breaking changes.

If I wanted to, for example, make an improvement that requires a breaking change in a library in another programming language, I could increment the major version to signify a breaking change (semvar). Programs using the library could lock the dependency to a major version to prevent pulling in breaking changes. Seeing that there is a new major version, someone could then read the library documentation to see the migration steps. With Emacs packages, there is no way to detect breaking changes other than looking at all packages individually. There is no way to prevent breaking changes on MELPA stable other than to never make a new release.

If you're worried about new bugs or breaking changes, I think the best solution currently is to use straight.el (or something similar, e.g. manually managed submodules) to lock versions and rollback when necessary.

**Comment by alphapapa** [comment]
> At some point I will finish a minimum rewrite of general (probably under a new package name)

@noctuid Off-topic, of course, but do you have an issue tracking that, or have you written more about it yet?  I'm curious about your plans, since I'm a big fan of `general`.  :)

**Comment by noctuid** [comment]
I thought there was already a dedicated issue, but apparently there wasn't. See #497.
