### ISSUE TITLE
general-key-dispatch + evil-surround compatibility note

### ISSUE THREAD

**Issue by AssailantLF** [noctuid/general.el#20]
When `general-key-dispatch` is applied to `c`, the `cs` "change surround" operator is broken, but is easily fixed.

The fix: add `evil-surround-change` as a sub-binding, just like `evil-change-whole-line`.

    (general-define-key :states 'normal
                        "c" (general-key-dispatch 'evil-change
                              ;; other sub-bindings
                              "c" 'evil-change-whole-line
                              "s" 'evil-surround-change))

I figure that since `evil-surround` is such a popular package, you may want to note this somewhere. Although the `general-dispatch-key` section of the README already has quite a lot of info tacked on :P

**Comment by noctuid** [comment]
Yeah, the less workarounds users have to do themselves the better. It is working for me without having to bind it explicitly though. I've made some changes since the last commit, but it seemed to work fine on master. I'll come back and look at this as soon as I make how `general-key-dispatch` handles removing duplicate/junk keys from `evil-repeat-info` more robust.

**Comment by noctuid** [comment]
Okay, it wasn't working before, but it should be working now without the need to explicitly bind the key. Let me know if it still doesn't work for you.

**Comment by noctuid** [comment]
Actually, I need to find a better way to handle this that doesn't break things.
