### ISSUE TITLE
Bindings not working with multiple instances of Eshell

### ISSUE THREAD

**Issue by marktran** [noctuid/general.el#32]
Thank you for this excellent package! I'm having an issue that I'm trying to figure out how to handle.

I have Eshell key bindings defined with the `use-package` keyword:
```
(use-package eshell
  :commands eshell

  :general
  (:keymaps 'eshell-mode-map
    "C-d" 'bury-buffer)

  (:keymaps 'eshell-mode-map
   :prefix "C-w"
   "=" 'balance-windows
   "h" 'windmove-left
   "C-h" 'windmove-left
   "l" 'windmove-right
   "C-l" 'windmove-right
   "j" 'windmove-down
   "C-j" 'windmove-down
   "k" 'windmove-up
   "C-k" 'windmove-up
   "C-o" 'delete-other-windows
   "c" 'delete-window
   "u" 'winner-undo)

  :config
  [...])
```

I start different Eshell instances for various projects via `projectile` and [projectile-run-eshell](https://github.com/bbatsov/projectile/blob/c7804740fc70f39e45d2b6a7a17b6f14318e369d/projectile.el#L2236):
```
(defun projectile-run-eshell ()
  "Invoke `eshell' in the project's root."
  (interactive)
  (let ((eshell-buffer-name (concat "*eshell " (projectile-project-name) "*")))
     (projectile-with-default-dir (projectile-project-root)
       (eshell))))
```

If I start Eshell for project `foo` and another Eshell for project `bar` then the key bindings I mentioned above will work in the first Eshell but not the second (or any subsequent Eshells).

How can I get the key bindings to work on all of my Eshells?

**Comment by noctuid** [comment]
Well the same thing happens if you just use `define-key` with `eshell-mode-map`. It looks like `eshell-mode-map` is buffer-local for some reason. Looking at `esh-mode.el`, it looks like this may not be intentional:

```
;; FIXME: What the hell!?
(setq-local eshell-mode-map (make-sparse-keymap))
```

Regardless of whether this is intentional, the problem is with eshell. As a workaround, I guess you could put your keybindings in a function and use `eshell-mode-hook` so they will be set up for every eshell buffer.

**Comment by marktran** [comment]
Ah, ok—I'll go with the `eshell-mode-hook` workaround. Thanks for looking into it.
