### ISSUE TITLE
contamination between :which-key when kbd differs between nmap and omap

### ISSUE THREAD

**Issue by sam217pa** [noctuid/general.el#36]
Let's say I want to bind `SPC s` to save-related stuff. 
```lisp
(general-define-key
 :prefix "SPC"
 :states '(normal)
 "s" '(:ignore t :which-key "save")
 "ss" 'save-buffer)
```
And now I want to bind `SPC s` to avy-goto-char in operator map
```lisp
(omap
 :prefix "SPC"
 "s" 'avy-goto-char)
```
I got a wrong result on my config when I press an operator. Say I press `d`, `SPC`, which-key indicates `save` instead of `avy-goto-char`.

Maybe it's a which-key related issue, but since I use the `:which-key` keyword of your awesome package, I submitted an issue here. 

Thanks !

**Comment by noctuid** [comment]
This is a which-key issue. If you make an issue on the which-key repo, I'd recommend not using `general-define-key` forms. For example, this is equivalent to your config (and causes the same problem):

```
(setq which-key-allow-evil-operators t)

(which-key-add-key-based-replacements "SPC s" "save")

(define-key evil-operator-state-map (kbd "SPC s") 'avy-goto-char)
```

I believe `which-key-allow-evil-operators` is considered experimental, so that is something to keep in mind as well.
