### ISSUE TITLE
Better cooperation between :prefix and :which-key

### ISSUE THREAD

**Issue by pdcawley** [noctuid/general.el#39]
I've added some stuff to the help map like so:

``` elisp
(general-define-key :keymaps 'help-map
  "A" '(nil :which-key "apropos"
  "A D" 'apropos-documention
  "A V" 'apropos-value)
```

But when I do `C-h` then `which-key` describes the `A` option as `+prefix`. As far as I can tell, it looks like `general-define-key` is calling `(which-key-add-key-based-replacements "A" "apropos")`, but that's never going to match the key sequence so far.

Your problem, or which-key's?

**Comment by noctuid** [comment]
This is the expected behavior; a full key sequence is required. If you use `:prefix "C-h"` instead of binding in `help-map`, it will work as you want to. Otherwise, you'll have to use `which-key-add-key-based-replacements` manually.

I'm don't think there is a way to determine the key(s) a prefix map is bound to given the prefix map's name (in this case, `help-map`). Without that, I can't implement this feature. I could infer the prefix keys for standard prefix maps, but that would only cover the standard prefix keys/maps and would be error-prone if the user rebound any of them.

**Comment by pdcawley** [comment]
Yup. I've managed to hack which-key to try `(keymap-prompt keymap)` when describing a prefix. So if I want different prompts depending on the prefix by which a map is looked up, I can do:

```elisp
(general-define-key :prefix my-leader
 "h" `(keymap "(H)elp" . ,help-map)
 "<f1>" `(keymap "f1 help" . ,help-map))
```

It's kind of gruesome, but I can hide that behind a macro and all's well.

**Comment by noctuid** [comment]
I could potentially add some potentially more convenient syntax directly to general if your PR is merged.

**Comment by pdcawley** [comment]
Initial prospects aren't promising I'm afraid, though it looks to me like there's a great deal of possibility inherent in `(menu-item "name" 'binding . plist)` as a mechanism for informing any `which-key` like system. If that works, then getting a decent entry in which-key becomes as simple as:

```elisp 
(defun define-named-key (map key binding name)
  (define-key map key
   (pcase binding
     ((pred keymapp) `(keymap ,name . ,binding)`)
     ((pred symbolp) `(menu-item ,name ,binding))
     (`(menu-item ,_ . ,rest) `(menu-item ,name ,@rest))
     (_ `(menu-item ,name ,binding)))))
```

And you don't have to worry about reusing the same map under multiple prefixes.

https://github.com/pdcawley/emacs-which-key/tree/feature/auto-describe-more-binding-types is looking promising (to me at least) but I need to sweat the details to make sure I'm producing a correct superset of the prompts that which-key generates.

**Comment by pdcawley** [comment]
Hm... actually, since `(menu-item "name" '(keymap …))` works, that's almost certainly a better choice 'cos then `name` can be an arbitrary lisp form which can be evaluated to build a contextual prompt. e.g. `(concat (if minor-mode "▣" "□") " toggle-minor-mode)`

**Comment by sondr3** [comment]
This would be really great, hope it works out 😃

**Comment by noctuid** [comment]
The menu-item approach was rejected, but now you could do something like bind `A` in `help-map` to a prefix map/command and use that as the match to make the replacement.

I could add a way to automatically create a prefix command/map in the binding and add another keyword to match the binding instead of the key:

`A '(:prefix-command 'apropos-prefix-map :which-key "apropos" :wk-match-binding t)`

I could have it default to matching the binding as long as there is one (vs. one with `:command nil` or `:ignore t`), so you wouldn't need an explicit `:wk-match-binding` most of the time. I could also add a `:wk-match-key`, so you could match both the key and binding. As for the the replacement, it could also be a cons or a function. I don't know if this is the ideal way to handle the original example, but I think I'll implement it like this to match which-key's new functionality.

**Comment by Chream** [comment]
Not a fix but it works. (It used bind-keys so kind of defeats the purpose I suppose.)

```
:config
(bind-keys
     :prefix-map ce-buffers-map
     :prefix "M-m b")
:general
(:keymaps 'ce-buffers-map
            "a"  'set-81-columns)
```

**Comment by noctuid** [comment]
General supports creating prefix maps already (with `:prefix-command`).

**Comment by noctuid** [comment]
This functionality has been added in the buttercup branch (the specific example in my earlier post is shown in the README; only `:which-key` needs to be specified). I will close this once the branch is merged.

**Comment by sondr3** [comment]
Any update on including this in `master`? 😃

**Comment by noctuid** [comment]
I'll try to work on things this weekend if I have time. If it's not merged within the next week or so, feel free to keep bumping this thread every one or two weeks, and I'll probably get to it quicker.

**Comment by sondr3** [comment]
No worries, take your time, just wanted to check in again.

**Comment by noctuid** [comment]
It's now merged. Please let me know if you find any problems.
