### ISSUE TITLE
Is it possible to define keybindings with priority higher than those defined with override keymap?

### ISSUE THREAD

**Issue by yangsheng6810** [noctuid/general.el#447]
I am using `M-hjkl` as visual movement keys (and some others), and want it to be universal in my config, so I have the following:
```emacs-lisp
(general-def
      :keymaps 'override
      :states '(motion insert normal visual)
      "M-h" 'evil-backward-char
      "M-j" 'evil-next-visual-line
      "M-k" 'evil-previous-visual-line
      "M-l" 'evil-forward-char
      "M-H" 'move-beginning-of-line
      "M-L" 'move-end-of-line
      "M-J" 'evil-scroll-down
      "M-K" 'evil-scroll-up
      "C-a" 'move-beginning-of-line
      "C-e" 'move-end-of-line
      "C-d" 'delete-char)
```
It would be a big hassle if I use `:keymap 'global`, since tons of packages bind keys on one or more of these keybindings. However, in some modes, I do would like to override some of the keybindings above. For example, in `vterm-mode`, I would like `C-a` to be mapped to `vterm-send-C-a`, or `vterm--self-insert`. I tried `:keymaps local`, but it still does not have a priority higher than `'override`. Is it possible to define keybindings with priority higher than those defined with override keymap?

**Comment by noctuid** [comment]
There's not currently a good way to do that. `:keymaps 'override :states 'normal` is using an intercept map, and `:keymaps 'local :states 'normal` isn't. Even if you make the local map an intercept map, it won't have precedence over the global one. I'm not sure if this is because evil prioritizes intercept maps that are created earlier or for some other reason. I don't think how evil prioritizes intercept keymaps is actually _defined/guaranteed,_ though it may matter. Maybe there is some workaround.

Probably the best way to do this currently is to use something like `general-predicate-dispatch` to select the definition based on the major mode.

You could also try creating a global minor mode and binding your keys in it with `:definer 'minor-mode` which will have higher precedence than most packages (see [evil keymap precedence](https://github.com/noctuid/evil-guide#keymap-precedence)).

**Comment by yangsheng6810** [comment]
Thanks for the response. I achieved my goal with `general-predicate-dispatch`. It is so cool!
Feel free to close the issue. BTW, do you think it a good idea to add a pointer to `general-predicate-dispatch` in the section for precedence of keybindings?
