### ISSUE TITLE
Keybinds dont work in some buffers (e.g. Messages)

### ISSUE THREAD

**Issue by sho-87** [noctuid/general.el#54]
I use `SPC` as a prefix to create a menu system similar to Spacemacs, however, in some buffers like the Messages buffer, `SPC` doesn't seem to be bound correctly. Here is how I have evil and general set up:

```
;; Evil
(use-package evil :ensure t
  :init (evil-mode 1)
    )

;; General
(use-package general :ensure t)

;; Menu system
(general-define-key
 :states '(normal visual emacs motion)
 :prefix "SPC"
 :non-normal-prefix "C-SPC"

 "SPC" 'helm-M-x
 
 "c" '(:ignore t :which-key "comment")
 "cl" 'comment-line
 "cr" 'comment-region

 "f" '(:ignore t :which-key "file")
 "ff" 'helm-find-files
 "fr" 'helm-recentf
 "fl" 'helm-locate
 "fs" 'save-buffer

  ;; etc.
 )

;; Markdown/GFM mode
(general-define-key
 :keymaps '(gfm-mode-map markdown-mode-map)
 :states '(normal visual emacs motion)
 :prefix ","
 :non-normal-prefix "C-,"

 "l" 'markdown-insert-hr
 ;; etc.
 )

;; Vim operations (delete, yank etc.) using avy
(general-evil-setup)
(general-omap
 :prefix "SPC"
  "jc" 'evil-avy-goto-char-2
  "jl" 'evil-avy-goto-line
  "jw" 'evil-avy-goto-word-1
  )
```
(my full `init.el` can be found here if its helpful: https://github.com/sho-87/dotfiles/blob/master/emacs/init.el)

In regular file buffers when I press `SPC` it correctly brings up possible keybinds under that prefix. But when I'm in a buffer like Messages that doesn't happen. Instead, every time I hit `SPC` I see `evil-forward-char: End of buffer`

It seems the `SPC` prefix is not working in these types of buffers. However, after using Emacs normally for a little bit, returning to the Messages buffer now correctly binds `SPC`

What's causing the `SPC` prefix to not work in the Messages buffer when I first start Emacs, but works a little while later?

**Comment by noctuid** [comment]
I don't think this would have anything to do with general. Could you see if the problem happens when using `define-key` instead? I don't have time to look into this right now, but I can later if necessary. I have a couple of initial suggestions, but I'm guessing they won't fix the problem. Try replacing `:states` with `:keymaps` in the `Menu system` keybindings. Also try running `(evil-normalize-keymaps)` and seeing if the keybindings become available. This issue is almost certainly related to evil.

**Comment by sho-87** [comment]
`(evil-normalize-keymaps)` doesn't seem to do anything, nor does changing `:states` to `:keymaps`

If I comment out all of my keybindings (everything using general in my first post) and then add `(define-key evil-normal-state-map (kbd "<SPC>bb") 'helm-mini)` then the Messages buffer correctly brings up helm mini buffer

Also, if I leave all of my original bindings but additionally include the `define-key` above, then regular file buffers will bring up the full menu when I press `SPC`. When I'm in the Messages buffer `SPC` will only bring up the 1 option for `<SPC>bb`, which suggests that General is not allowing the full menu to display in Messages, but bindings defined with `define-key` are showing up just fine

Of course, I haven't tried to reimplement the full menu using `define-key` to see if everything else works...

**Comment by sho-87** [comment]
I thought that maybe Messages is expecting me to use the `non-normal-prefix` I defined, so I also tried pressing `C-SPC` in that buffer, but it just prints a message saying `Mark activated`. Is General not overriding emacs keybindings in that buffer for some reason?

**Comment by noctuid** [comment]
Are you sure that using `:keymaps` doesn't fix the problem? I just tried two minimal configs with `emacs -Q` and was able to replicate the issue with `:states` but not `:keymaps`.

```

(package-initialize)
(require 'evil)
(evil-mode)
(require 'general)

;; Menu system
(general-define-key
 :keymaps '(normal visual emacs motion)
 :prefix "SPC"
 :non-normal-prefix "C-SPC"
 "" nil
 
 "SPC" 'helm-M-x
 
 "c" '(:ignore t :which-key "comment")
 "cl" 'comment-line
 "cr" 'comment-region

 "f" '(:ignore t :which-key "file")
 "ff" 'helm-find-files
 "fr" 'helm-recentf
 "fl" 'helm-locate
 "fs" 'save-buffer

  ;; etc.
 )
```

That worked for me.

**Comment by sho-87** [comment]
ah I was missing the `"" nil` for keymaps to work. It seems to be OK now with that change

whats the reason for this working with keymaps but not states? It seems states would be the intuitive thing to use here given Im setting bindings depending on an evil state

**Comment by noctuid** [comment]
Yeah, without the `"" nil" there will be an error, and the keys will never be bound because SPC is bound by default.

`:keymaps` is generally what you should use (`:keymaps 'normal` corresponds to binding a key in the global `evil-normal-state-map`). When you use `:states`, `evil-define-key` is used. Generally you should only use `:states` when you specify `:keymaps` unless you have a good reason to do otherwise (e.g. because eybindings made with `evil-define-key` don't always work immediately). General's readme [explains this](https://github.com/noctuid/general.el#notes-for-evil-users) in a little more detail. Let me know if there is anything I should add/change to make it more clear.
