### ISSUE TITLE
Some bindings not shown in general-describe-keybindings

### ISSUE THREAD

**Issue by ambihelical** [noctuid/general.el#60]
I have some bindings not bound to any particular evil state, an excerpt of their configuration is shown below.  These do not show up in general-describe-keybindings.  Shouldn't they?

```
  (general-define-key
    "<f2>"       #'ivy-switch-buffer
    "<f3>"       #'me:find-some-files
    "C-x b"      #'ivy-switch-buffer
   ...
```

**Comment by therockmandolinist** [comment]
I'm _only_ seeing insert-state keybindings. Weird.

**Comment by noctuid** [comment]
The development branch has changed a lot, and I cannot replicate this issue on it. If you are willing, could you test it and see if the problem persists? If you do, be prepared to switch back to the master branch though in case you encounter any other problems. Please see #7 for more information changes I just made to `general-describe-keybindings`; I've never closed it because I know it still needs work.

**Comment by noctuid** [comment]
I think I found the problem and will look into fixing it when I get the chance soon.

**Comment by noctuid** [comment]
It should be fixed on master now. I'll reopen this if you find some keybindings are still not showing up.

**Comment by ambihelical** [comment]
It seems to work now. Thanks.
