### ISSUE TITLE
Question regarding binding in org-src-mode-map

### ISSUE THREAD

**Issue by therockmandolinist** [noctuid/general.el#61]
Excellent package, first of all! It's letting me do things in a clean way that I previously had tons of hairy helper code for. Anyway, I have the folllowing setup for global and major/minor mode leaders:

```emacs-lisp
  (general-create-definer
   diego/leader-keys
   :states '(emacs normal visual motion insert)
   :non-normal-prefix "C-SPC"
   :prefix "SPC")

(general-create-definer
   diego/mode-leader-keys
   :states '(emacs normal visual motion insert)
   :non-normal-prefix "C-,"
   :prefix ",")
```

This works well for the most part, but I tried to do this:
```emacs-lisp
(diego/mode-leader-keys
 :keymaps 'org-src-mode-map
 "'" 'org-edit-src-exit)
```
and for some reason, it's only letting me access that key with the insert-state leader in org-src-mode (`C-SPC`) and not the normal-state one (`SPC`). Do you know what could be happening here?

**EDIT:** I don't have this issue when i bind to, say, org-mode map, and I also realized this is bound correctly in org-src-mode-map in every other evil state but normal.

**EDIT 2:** It's allowing me to access the binding if I first switch from insert state to normal state (or manually call `evil-normal-state`), then do `, '`.

**Comment by noctuid** [comment]
I believe [this is issue](https://github.com/noctuid/evil-guide#why-dont-keys-defined-with-evil-define-key-work-immediately) you are facing. You either need to use the org src mode hook or use `evil-define-minor-mode-key`. The development branch allows doing this with `:definer 'minor-mode` (see [here](https://github.com/noctuid/general.el/tree/buttercup#wrapping-evil-define-minor-mode-key)).

**Comment by therockmandolinist** [comment]
Thanks, the mode hook works for now! Any idea when the buttercup branch will be merged? (I only ask since I see there's a couple commits on master that aren't on there, so I'm not sure how I'd be affected if I switched to that branch now)

**Comment by noctuid** [comment]
It will probably be a while. I won't have much time to work on this package for at least a month, and I still need to do a lot of work on the branch (e.g. finish rewriting all tests). Because the tests are not yet completed, I'm not doing a very good job ensuring nothing breaks between commits on that branch, so I wouldn't necessarily recommend using it. I will rebase so it has the latest commit from master; that is the only bug I am aware of that exists on the buttercup branch but not on master. I am using the branch myself, but I'd recommend being ready to switch back if you do try it out. And if you do try it, I'd appreciate any feedback.
