### ISSUE TITLE
Add Key Documentation Functionality

### ISSUE THREAD

**Issue by noctuid** [noctuid/general.el#7]
Like with `bind-key` there would be an optional `:doc` keyword to support associating a string with a prefix sequence. There would also be a function that would display all keys bound with general.

Edit:
- [X] Basic functionality
- [X] Displaying last keybinding
- [x] Optionally never replace last keybinding (will always show original)
- [x] Handling long lines and menu-item
- [x] Maybe user-customizable order and user-customizable displayed items

**Comment by blaenk** [comment]
This is probably a tall order or beyond the scope, but it would be awesome if it could somehow integrate with [helm-descbinds](https://github.com/emacs-helm/helm-descbinds) or otherwise create a separate helm source for this, so one could quickly see and filter through the various bindings.

For example it's nice that with bind-key I can do `describe-personal-keybinds` but it puts it in a boring buffer that I have to manually search through. On the other hand helm-descbinds is amazing for quickly narrowing and looking for that one bind you forgot about. The awesome thing is that like `describe-personal-keybindings` it shows from which modes/maps the binds are from, even as you narrow down.

It looks like helm-descbinds already has most of the "infrastructure" for showing keybinds, so if it is possible to simply feed it a list of the binds that it should use instead of it looking for the binds on its own as usual, we could leverage the existing code for it.

It looks like it [uses `describe-buffer-bindings` to source itself](https://github.com/emacs-helm/helm-descbinds/blob/master/helm-descbinds.el#L147), then it parses out the bindings. So if we could create a buffer with the same format then we can leverage the existing code. Then again since we're producing the list of binds ourselves, maybe we can feed that directly instead of round-about producing a buffer for helm-descbinds to parse back out. That function shows what format it expects for the list of keybinds which is called `sections` there.

``` elisp
;; for headers, i.e. for a given keymap
(push (cons header (nreverse section)) sections)

;; for the actual binds
(push (cons key binding) section))
```

Then one would be able to bind such a helm command to some key for example to quickly see all of the bindings _they've_ specifically created and quickly narrow through them to find the binding that one forgot, or even just to browse through very quickly.

**Comment by blaenk** [comment]
Also I forgot to mention that it would be cool if general.el records the fact that a binding may have been unbound by the user, e.g. by binding to `nil`, so that in some representation of the binds the user has created it would say "C-x was unbound" or something, which may be helpful if they're wondering why the key isn't working and forgot they had unbound it.

That's a minor thing though so if it's too difficult to implement it's not a big deal. Also it wouldn't be relevant to the above helm-descbinds integration unless it's possible to show a candidate in helm which can't be chosen (since it wouldn't make sense), which I wouldn't be surprised if it was possible, since there's already support for things like headers.

**Comment by noctuid** [comment]
> it would be awesome if it could somehow integrate with helm-descbinds

If I were to do something like this, I wouldn't want it to be limited to helm; it should also work with ivy, for example. I have no experience with creating helm sources either. I can look into doing this at some point, but for now it is a low priority (I'll look at it after I get other functionality working).

> On the other hand helm-descbinds is amazing for quickly narrowing and looking for that one bind you forgot about

It's not as nice, but you could still search for keybindings with helm-swoop or swiper.

> The awesome thing is that like describe-personal-keybindings it shows from which modes/maps the binds are from, even as you narrow down.

Fwiw, I'm going to use org mode for the output buffer with headings corresponding to the keymaps and states, so it should be pretty easily searchable (e.g. with `helm-org-in-buffer-headings` or `worf-goto`). Maybe there is a way to display the org headings when narrowing with something like helm-swoop, or maybe creating a source for helm would be easier.

> if we could create a buffer with the same format then we can leverage the existing code.

That wouldn't be too hard. One thing of note is that `describe-buffer-bindings` shows keys bound for a state and a keymap (e.g. with `evil-define-key`) as something like `\`t' Minor Mode Bindings`. I guess I'd replace that with something like `Org Mode/ Normal State Bindings:`. Again, I'd like something compatible with ivy, but I don't know if ivy can have sections/headings (yet), so I'll have to look into that as well.

> That function shows what format it expects for the list of keybinds which is called sections there.

That looks like it would be even easier.

> it would be cool if general.el records the fact that a binding may have been unbound by the user

Would it be okay to just show something as bound to `nil` or `Unbound`?

**Comment by blaenk** [comment]
Yeah on second thought I wouldn't worry about this. If you could maintain a list of keybinds like bind-key does which can be retrieved either from a variable or from a function, then I could play around with creating a helm source for it, likewise with ivy, since I'm not sure if something that can be used with both out of the box would look well (I imagine it'd use something like completing-read or whatever), but once we have access to such a list it should be easy to create our own to experiment with and possibly contribute back, so there'd be one for ivy and helm.

Then again perhaps completing-read would be enough, but I like in helm-descbinds how it keeps track of which binds are from which maps, even as you narrow down.

But yeah I agree I'd leave it as a low priority as long as you maintain a list that people can get and play with, if possible. I know it's possible to search through a buffer easily enough and it's definitely better than nothing, but there's something so quick and fluid about using something like helm-descbinds or yes an equivalent in ivy.

**Comment by noctuid** [comment]
Okay, I've thrown together an initial working `general-describe-keybindings`. The keybindings are displayed as tables in an org buffer where the top headings correspond to keymaps and the level 2 headings (when they exist) correspond to evil states. Global keybindings are shown first followed by global evil keybindings (e.g. keys bound in `evil-normal-state-map`). Keys (and keymaps) are kept in the same order that they were defined in.

![2016 05 31_01 21 19_-_emacsbaphamet](https://cloud.githubusercontent.com/assets/4250696/15664392/3d0232fe-26d1-11e6-9448-5ef415a13a06.png)

>  If you could maintain a list of keybinds like bind-key does which can be retrieved either from a variable or from a function

The keybindings are stored in `general-keybindings`. The format may not be very friendly for use with a helm source or something else; it's a nested alist. I could make a function to convert it to whatever would be more convenient for this.

Right now there are a few things still missing.

It doesn't display local keybindings. I'm not sure what the best way to handle/display local keybindings would be. I could maybe have a separate variable that would be buffer local and contain the keybindings for that buffer. I guess local keybindings should be displayed first.

I haven't added a `:doc` keyword for prefixes. I'm not sure how useful it really is. I'm also not sure where I would put prefix documentation or when it would make sense to differentiate between the same key. Would the documentation for a prefix key be global? Maybe there should be both a `:global-doc` and `:doc`. Then should `:doc` apply for the entire keymap (as opposed to for a combination of a keymap and a state if there is one).

Also, I haven't yet added code to prevent duplication of keybindings (if the same key is bound multiple times, only the last binding should be displayed).

**Comment by blaenk** [comment]
Good work!

I agree with the way you plan on handling local keybindings. I can't really comment on `:doc`. I'm reminded though of how you can [explicitly write strings](https://github.com/justbur/emacs-which-key#custom-string-replacement-options) for keys in which-key, it'd be cool if that were possible through general.el so one wouldn't have to write things twice but I don't really see how that'd be possible without too much effort. Maybe if you could add a `:doc` keyword argument to each binding, like:

``` elisp
(general-define-key :keymaps 'blah
  "C-x" 'thing :doc "do that thing"
  "C-y" 'other :doc "do that other thing")
```

but anyways I digress.

**Comment by noctuid** [comment]
> so one wouldn't have to write things twice

Do you mean as a separate step?

> Maybe if you could add a :doc keyword argument to each binding

The way you add descriptions for which key isn't really analogous to how you bind keys in general, and having a `:doc` keyword for every mapping would really complicate things. I can't think of any nice looking syntax for this and would rather not add this functionality.

One an unrelated note, do you think that it would be preferable to defer adding the keys until they are actually bound (the keymap exists) as opposed to adding them immediately?

**Comment by blaenk** [comment]
> Do you mean as a separate step?

Yeah so like having to write the bind and then write it out again to specify the which-key string. But yeah it's not a big deal and it's not that common to want to add strings anyways, it was more of a fleeting idea.

> On an unrelated note, do you think that it would be preferable to defer adding the keys until they are actually bound (the keymap exists) as opposed to adding them immediately?

This is distinct from adding them until the command is autoloaded right? Because in that case we'd want to show them right away since pressing the keybind is what would load it.

If you specifically mean when the keymap itself exists, that's actually a good question. I guess the analog in bind-key would be to put it in a with-eval-after-load, so the bind-key wouldn't actually run until the package is loaded and the keymap exists, so bind-key will not have registered the personal bind until then as well. I guess that's the least potentially surprising option. Consider if for some reason the package _never_ loads but the user clearly sees the bind is present in the personal bindings listing, it would probably be confusing. If they don't see the binding there at all then they can probably deduce that the package isn't loading. What do you think?

**Comment by noctuid** [comment]
> This is distinct from adding them until the command is autoloaded right?

Yes.

> it would probably be confusing

I think that you're right. Now the keybindings will be added at the same time they are created.

Local and duplicate keybindings are now handled. I've decided not to add `:doc` for prefix keys unless someone wants it and gives a description of how it should act.

**Comment by blaenk** [comment]
Cool!

**Comment by stepnem** [comment]
One useful feature still missing in `general-describe-keybindings` (and present in bind-key.el) is information about the original bindings of rebound keys. Any plans to implement that?

**Comment by noctuid** [comment]
Yes, I will look into adding that feature as well when I have the time.

**Comment by noctuid** [comment]
The previous keybindings are now displayed on the development branch, but I have yet to add an option to to display original keybindings if a key is defined twice (currently the previous keybinding will be updated each time). I've added some checkboxes to the original post as well.

**Comment by stepnem** [comment]
Seems to work fine (c24e75c AKA current tip of the buttercup branch),
thank you very much!

I wonder though if this feature shouldn't be builtin, similarly to how
you get information about previous values of customised variables in
`describe-variable`. After all it's not feasible to make all 3rd party
code one loads use general (or bind-key or what have you) when rebinding
keys, while it would definitely be helpful to be able to inspect all
such rebindings.

**Comment by noctuid** [comment]
>  After all it's not feasible to make all 3rd party code one loads use general (or bind-key or what have you) when rebinding keys

This is possible by advising `define-key`. I could potentially look into adding a feature like this in the future.

**Comment by stepnem** [comment]
>>  After all it's not feasible to make all 3rd party code one loads use general (or bind-key or what have you) when rebinding keys
>
> This is possible by advising `define-key`. I could potentially look into adding a feature like this in the future.

Yeah, but that's more on the kludgy side, plus you'd still have to make
sure the advice is activated before any rebindings take place.

**Comment by noctuid** [comment]
The development branch is now merged and all planned functionality is implemented. Sorting is now customizable, and it is possible to only replace the previous binding when the definition changes or when the key was previously unbound. There is not an option to only store the previous definition only the first time a key is bound though (e.g. if you bound a key, unbound it, then bound it again, the previous definition would show up as the first thing you bound the key to). If someone wants this behavior, please make a separate issue. I don't think it would generally be useful.

Longer keys/definitions are truncated to 50 characters.

I won't implement the ivy/helm idea myself because I don't think it adds much over the org buffer. I'm open to pull requests though.

> Yeah, but that's more on the kludgy side, plus you'd still have to make sure the advice is activated before any rebindings take place.

The only downside I see is that you'd have to use the keymap prompt instead of the name (since you can't advise with a macro). I do agree that something like this would make more sense builtin. Maybe `M-x report-emacs-bug`.
