### ISSUE TITLE
Add key repeat functionality

### ISSUE THREAD

**Issue by ambihelical** [noctuid/general.el#72]
It would be great if general implemented a feature that allowed the most recent command to be repeated by typing the last character of the key binding.  An example:

`(general-define-key :repeatable (kbd "s-n") 'next-error)`

After entering super-n, each subsequent n key would execute the command again until some other key is entered.  I've seen this implemented on a package basis, e.g. https://github.com/nonsequitur/git-gutter-plus/pull/30, but this functionality fits well into the general framework and would be a great addition.

**Comment by noctuid** [comment]
I agree that this would be useful; I'll add it. It will be specifically for `evil-repeat` though and will be the same as using `evil-add-command-properties` (e.g. `:repeat t`, `:repeat 'abort`, `:repeat 'motion`, etc.). I'll also add some way to add any type of command property.

**Comment by noctuid** [comment]
This is now implemented. See [here](https://github.com/noctuid/general.el#evil-command-properties)

**Comment by ambihelical** [comment]
@noctuid A late thanks for this, the feature as you implemented has been useful.  However, is there any chance this could be done as described as well (using a different keyword I suppose), or do you consider it out of scope of general.el?  I realize now that I gave a bad example, this would be useful after a sequence starting with a prefix. e.g. "SPC xy", not key+modifier.   After I execute a command via a sequence, my finger is already on the last key, so it is faster than typing "." to repeat.

**Comment by noctuid** [comment]
Yeah, I consider functionality like that outside the scope of this package. You can use hydra instead to do that if you'd like.

**Comment by ambihelical** [comment]
I already get key prompting for prefixes from which-key, so its a bit of an overkill.  I'm using hydras for a couple things--it isn't simple to set up, and is fairly intrusive, you enter the hydra with one key, and there is a ui of sorts, it isn't transparent at all.  For some things it's great, but it won't really do what I'm after.  In any case, since you don't want to add the functionality to general.el I'll look for some other way to do it.

**Comment by noctuid** [comment]
Prompts are not the primary feature of hydra; they are extra and can be disabled. The setup is not particularly tedious:

```elisp
(setq hydra-is-helpful nil)

(defhydra my-error-hydra ()
  "error navigation"
  ("n" next-error)
  ("p" previous-error))

(general-def 'normal
  "SPC x" 'my-error-hydra/body)
```

The only real issue is that you can't add more keys/heads later (see abo-abo/hydra#185). If `hydra-add-head` existed in hydra, it would be easy for general.el to bind in existing hydras. General.el could also automatically create hydras. For example, the previous hydra could be written like this:
```elisp
(general-def 'normal
  :prefix "SPC x"
  ;; for random name
  ;; :prefix-hydra t
  :prefix-hydra 'my-error-hydra
  "n" 'next-error
  "p" 'previous-error)
```

New keybindings could be added to a hydra later (e.g. `:definer 'hydra`), and hydra's keywords could be used in extended definitions. 

It seems to me like hydra does exactly what you want. The PR you linked to earlier basically works the same way as hydra. I'd much rather have general.el wrap hydra than re-implement a small portion of its functionality.

**Comment by ambihelical** [comment]
I tried it.  There are a number of problems:
1. hydra-is-helpful is global, and it actually only changes the hint in the echo area, the popup is still shown at the start of the hydra.  Even if it worked they way you indicated, I have other hydras that I want to keep with a popup. I'm sure others would feel the same. 
2. Even if I'm ok with UI, there must be an exit key (even when :timeout is used). This makes it a bit less transparent than I would want.  :timeout seems to affect the hint in the echo area only, this is shown after the first key is pressed and when the hydra is sticking around. 
3. There are problems with redefining an existing prefix.  e.g. C-w for window ops.   This is probably my inexperience with elisp and/or hydra, but I haven't gotten anything to work satisfactorily.   OTOH I had no difficulty adding :repeat to existing keys using general.

**Comment by noctuid** [comment]
1. Any global variable can be changed for a single function using `let` and lexical binding. If you would prefer to use a hydra keyword to customize this locally, I'd suggest making an issue. Even if this isn't added, it would be easy to add a keyword to a general.el wrapper to do this. There should not be a popup when `hydra-is-helpful` is nil; there isn't for me.

2. By default all keys not explicitly bound in the hydra are exit keys. Isn't this the behavior you wanted? If you want to be able to use `:timeout` as the only means of exiting the hydra (e.g. you've specified `:foreign-keys warn`), you should request this feature.

3. Could you elaborate? I don't understand this issue.

I agree that it would it would be nice to have this functionality in general.el. One way or another I'd like this to be possible. Ideally hydra would be used, and the simple syntax you want would be possible via general.el. See the new linked issue. If it turns out there's some fundamental issue with hydra that won't be fixed, I'll reopen this issue.

**Comment by ambihelical** [comment]
I basically got it to work.  I didn't think I could use lexical binding for the defhydra because it's a macro, but wrapping the defhydra in an eval seems to work.   #2 was a simple bug/misconfig. #3 was caused by using hydra's keybinding.  Using general.el's works.  

The main remaining pain points may well be helped by wrapping hydra in general.el because I have to define each binding twice.  Once to kick off hydra using the hydra defined namespace using general keybinding facilities.  And once again in the hydra itself.   Here is what I have so far (hack code, not final):

```
(use-package evil
   ....
:general
   ...
  (:keymaps '( normal insert visual ) :prefix "C-w"
              "-"  #'hydra-windows-navigation/evil-window-decrease-height
              "="  #'hydra-windows-navigation/evil-window-increase-height
              ","  #'hydra-windows-navigation/evil-window-decrease-width
              "."  #'hydra-windows-navigation/evil-window-increase-width)
  ...
 :config  
  (defun me:set-up-windows-hydra ()
    (let ((hydra-is-helpful nil))
      (eval
        '(defhydra hydra-windows-navigation (:foreign-keys exit :exit nil :timeout 2 :hint nil )
          "window navigation"
          ( "-"  #'evil-window-decrease-height "shorter")
          ( "="  #'evil-window-increase-height "taller")
          ( ","  #'evil-window-decrease-width "thinner")
          ( "."  #'evil-window-increase-width "fatter")))))
  ....
  (evil-mode 1)
  (me:set-up-windows-hydra))
```

**Comment by ambihelical** [comment]
A less major pain point is the namespacing that hydra uses.  It wants a unique name for each hydra so the fabricated name tends to be quite long, and tends to make the which-key popup pretty crowded.   I'd rather it let me provide separate body & head namespaces so I can use something short for the heads as the command tends to make the name unique anyway.  I may try to see if that change can happen in hydra.
