### ISSUE TITLE
Regression for keybindings with unnecessary '() wrapping

### ISSUE THREAD

**Issue by terlar** [noctuid/general.el#76]
I noticed this regression during a recent update, this has been working before.
I know that it might be incorrect and it works if I just write `'previous-buffer`, and also if I add some keywords inside there like `:package`. Thought I let you know since it is a regression.

Here are the steps to reproduce:

Pre-steps:
- `M-:`
```
(setq package-archives '(
  ("gnu" . "https://elpa.gnu.org/packages/")
  ("melpa" . "https://melpa.org/packages/")))
```
- `M-x` `package-install` `general`

Setup key-binding:
`(general-define-key "C-c p" '(previous-buffer))`

Press key-binding: `C-c p`

Output:
```
Debugger entered--Lisp error: (wrong-type-argument commandp (previous-buffer))
  call-interactively((previous-buffer) nil nil)
  command-execute((previous-buffer))
```

**Comment by noctuid** [comment]
This is intentional or at least it isn't considered a valid extended definition. Extended definitions must contain keywords (otherwise there is no point in using them). I don't want to add extra checks to allow this to work.

Thanks for the bug reports though. Merging the development branch has changed general a lot, so the sooner I find any untested issues the better.
