### ISSUE TITLE
Document use of `:name` arg when using general-key-dispatch in multiple modes

### ISSUE THREAD

**Issue by jamesnvc** [noctuid/general.el#87]
I recently was fairly confused by the behavior of `general-key-dispatch`.
I was trying to make a mapping like vim-fireplace, so I could use `cpp` to evaluate the sexp under the cursor in Clojure and in Emacs-Lisp.
To do this, I had something like
```
(general-nmap :keymaps 'cider-mode-map
              "c" (general-key-dispatch 'evil-change
                    "pp" 'cogent/cider-eval-next-sexp
                    "c" 'evil-change-whole-line))

(general-nmap :keymaps 'emacs-lisp-mode-map
              "c" (general-key-dispatch 'evil-change
                    "pp" 'cogent/elisp-eval-next-sexp 
                    "c" 'evil-change-whole-line))
```

What ended up happening though, was the key binding in Clojure was trying to eval the form using the emacs-lisp function.
I eventually realized that the function that `general-key-dispatch` created was being overridden and the solution was to include a `:name` argument in the call.

I think the documentation for general-key-dispatch should contain some sort of warning, to the effect of "If you have a mode-local key binding to `general-key-dispatch`, you should include the `:name` parameter to avoid conflict with using a dispatcher to the same function in other modes".

**Comment by jamesnvc** [comment]
I see that there's a similar warning about needing `:name` with multiple `self-insert-commands`, but for whatever reason, I assumed that didn't apply to having bindings for multiple modes.

**Comment by noctuid** [comment]
Thanks for opening this issue. `general-key-dispatch` is just a function creating macro and knows nothing about the keymap it is being bound in. In the past, it used to allow returning an anonymous function, so this wasn't an issue in those cases. Most people use it directly in a key definition (as if it returned a lambda), so I may start appending a random string to the function name (and ensuring that it isn't already bound) instead of requiring the user to use `:name`. If the user wanted to explicitly name the function, they could use `:name`, or I could potentially provide another macro with `define` in the name.

As a side note, with the current version of general.el and default setup, you can write `general-nmap emacs-lisp-mode-map` without the `:keymaps`.

**Comment by noctuid** [comment]
Using `:name` is no longer necessary to prevent this issue as the automatically generated names are now unique.
