### ISSUE TITLE
Latest version of use-package together with :general keyword and :demand t has issues

### ISSUE THREAD

**Issue by terlar** [noctuid/general.el#88]
I just found out after upgrading to the latest `use-package` that if I use `:general`-keyword together with `:demand t` it is not loading the package at all, it also doesn't create the auto-loads for the functions, so the bindings end up being non-existing, a workaround is to add all the specified bindings in `:commands` also, but if I remember correctly that was not needed before.

I am not sure where the issue is exactly and have created a issue at [use-package](https://github.com/jwiegley/use-package/issues/532). Just a heads-up if it is some protocol that has changed or if you have seen similar issues.

**Comment by noctuid** [comment]
I cannot replicate either of these issues. It works as expected for me with the latest use-package commit. Can you try reproducing this with a minimal configuration and give me a full example of a use-package statement?

**Comment by noctuid** [comment]
Alright, I saw the comments on the use-package issue and will make the necessary changes when I have some free time.

**Comment by terlar** [comment]
Sorry for the lack of feedback, I was going to refer to that, but also wanted a reproducible use case with minimal setup, but couldn't do that, so guess there are some more factors. But luckily the maintainer of use-package was quick to understand the issue anyways. Thank you.

**Comment by jwiegley** [comment]
I've made further changes that would affect how the use-package extensions for general are implemented. Please see the latest version of the `NEWS.md` file for the notes. Particularly these:

- The ordering of several elements of `use-package-keywords` have changed; if
  you had previously customized this (or were an extension author adding to
  this list), you may need to rework your changes.

- For extension authors, the way `:commands` are propagated down for
  autoloading has changed. They used to be passed through the `state`
  parameter, but are now done as an extension to `rest`. Please see
  `use-package-handler/:bind` for a canonical example.

- For extension authors, if you add a keyword to `use-package-keywords` whose
  presence should indicate deferred loading, please also add it to
  `use-package-deferring-keywords`. Note that this is a bit of a sledgehammer,
  in that the mere presence of these keywords implies deferred loading. For a
  more subtle approach, see the new `use-package-autoloads/<KEYWORD>` support
  mentioned in the next bullet.

- For extension authors, if you wish deferred loading to possibly occur,
  create functions named `use-package-autoloads/<KEYWORD>` for each keyword
  that you define, returning an alist of the form `(SYMBOL . TYPE)` of symbols
  to be autoloaded. `SYMBOL` should be an interactive function, and `TYPE` the
  smybol `command`, but this functionality may be extended in future. These
  autoloads are established if deferred loading is to happen.

- If you specify a lambda form rather than a function symbol in any of the
  constructs that *might* introduce autoloads: `:bind`, `:bind*`,
  `:interpreter`, `:mode`, `:magic`, `:magic-fallback`, and `:hook`: then
  deferred loading will no longer be implied, since there's nothing to
  associate an autoload with that could later load the module. In these cases,
  it will be as if you'd specified `:demand t`, in order to ensure the lambda
  form is able to execute in the context of the loaded package.

**Comment by dieggsy** [comment]
To clarify a point in the original isssue, the problem is not just with `:demand t` - I'm seeing no autoloads generated at all through `:general`

**Comment by noctuid** [comment]
@terlar @dieggsy Please test. It should be working now.

**Comment by terlar** [comment]
Seems to work, thank you :+1:

**Comment by dieggsy** [comment]
Confirmed
