### ISSUE TITLE
Non-prefix key error but still working?

### ISSUE THREAD

**Issue by schoettkr** [noctuid/general.el#97]
My setup worked perfectly fine, however I recently reinstalled Emacs and therefore updated all packages as well when starting for the first time.

Since then I cant get rid of the warning/error: 
`Error (use-package): general/:config: Key sequence SPC x starts with non-prefix key SPC`

Relevant part of my config:

    (general-define-key
       :states '(normal emacs motion)
       :prefix "SPC"
    
       "x" 'counsel-M-x )

I already tried:

 - unbinding SPC before it is used as a prefix
 - have my keybindings load after everything else
 - using alternative definitions for using spacebar  to "SPC" for example with kbd

What is especially weird to me, is that the keybinding and all others that are prefixed with `SPC` work perfectly fine like they should (even `SPC x`). `C-h k SPC` also gives me the associated results.

I cannot get rid of this error, any help is appreciated I am still kind of new to Emacs :)

**Comment by noctuid** [comment]
The reason this has changed is because [the behavior of `:states` has changed](https://github.com/noctuid/general.el#2018-01-20-states-normal-is-now-the-same-as-keymaps-normal). Previously your example was not binding in `evil-motion-state-map` and now it is. It's likely that you did not correctly unbind `SPC` in `evil-motion-state-map`. Your keybindings still work because `SPC` is not bound in `evil-normal-state-map` by default, so that keybinding succeeds before the error. Generally, it doesn't make sense to bind the thing in both the motion and normal state keymaps. Also, are you sure that you want to bind `SPC` in emacs state (this means that you will not be able to insert `SPC` when in emacs state)?

In the general case, `"" nil` can be added as the first keybinding to unbind a prefix key in the relevant keymaps. Alternatively, general now has an experimental feature that will automatically unbind keys whenever necessary to prevent this error that you can try if you wish by adding `(general-auto-unbind-keys)` to your config (though the name of this function may change in the future).
